### ISSUE TITLE
Gyakuten Saiban 3 - Neverending note

### ISSUE THREAD

**Issue by yopox** [ipatix/agbplay#17]
I found a problem on track 0306 in Gyakuten Saiban 3 (ROM `A3JJ`).
There is a neverending note on track 4 (around location `0x01436C7`).

You can compare [this rip](https://youtu.be/kIaPW-YNlRw?t=1h3m55s) and a [wav exported with agbplay](https://mega.nz/#!x9YBgYYB!ousodbudrkI3zQE7tOctcFQNhfWUE8DkO3Z6B2rqrNU) (happens just after 00:45).

**Comment by ipatix** [comment]
I'll have a look at it.

**Comment by ipatix** [comment]
Sorry for being a bit slow. Just wanted to let you know I can confirm the problem and I'm working on it.

**Comment by ipatix** [comment]
Seems like for some reason agbplay starts to play the notes on the wrong track after looping.

**Comment by ipatix** [comment]
^got this. Works now
