### ISSUE TITLE
Add a --help switch

### ISSUE THREAD

**Issue by nicholatian** [ipatix/agbplay#2]
Was surprised to find this program doesn’t provide any sort of command-line `--help`.

Could you add this so people know how to address the binary and give it the things it needs? It looks like I’ll be poking at it until I figure out what works…

**Comment by ipatix** [comment]
I'll hopefully do that in the next few days.

**Comment by ipatix** [comment]
I added a basic --help option:

`$ ./agbplay.exe --help
Usage: ./agbplay <ROM.gba>

Controls:
  - Arrow Keys or HJKL: Navigate through the program
  - Tab: Change between Playlist and Songlist
  - A: Add the selected song to the playlist
  - D: Delete the selected song from the playlist
  - T: Toggle whether the song should be output to a file (see R and E)
  - G: Drag the song through the playlist for ordering
  - I: Force Song Restart
  - O: Song Play/Pause
  - P: Force Song Stop
  - +=: Double the playback speed
  - -: Halve the playback speed
  - N: Rename the selected song in the playlisy
  - E: Export selected songs to individual track files (to "workdirectory/wav")
  - R: Export selected songs to files (non-split)
  - B: Benchmark, Run the export program but don't write to file
  - Q or Ctrl-D: Exit Program
`
