### ISSUE TITLE
Add option to specify path to agbplay.ini, and default it to a sane location

### ISSUE THREAD

**Issue by nicholatian** [ipatix/agbplay#27]
`agbplay` apparently always looks in the current working directory for its INI file, with no way for the user to command it otherwise. This makes it impossible to package for distros as I discovered: I put together an AUR PKGBUILD and this unfortunately halted my work.

My recommendation is to keep the current behaviour, but add a CLI option to specify it, and also make the program fall back to look in `/usr/share/agbplay/` for the INI if it isn’t found in `$PWD`. This would be perfect for my PKGBUILD.

**Comment by ipatix** [comment]
Tbh, the only reason why it uses the working directory is because I was lazy when I initially developed it. I'd say it would make most sense to remove this default behaviour and use an .ini in /etc, in ~/.config/, or in /usr/share/agbplay (as you mentioned).
Does this sound like a "sane" idea? If so, would /usr/share/agbplay or /etc the right place for this kind of thing?

**Comment by nicholatian** [comment]
it's good you mentioned that. If I know UNIX like I think I do, `/etc/agbplay.ini` would be a more appropriate path. User-local paths are good too, I suppose `~/.config/agbplay.ini` would do.

**Comment by ipatix** [comment]
Okay, agbplay now uses the following paths:
- `/etc/agbplay.json`: This file is only read.
- `~/.config/agbplay.json`: If it exists, this file is now used for storing all the state which previously was in the working directory. If it doesn't exist, the etc path above is used. If none exist, this file is created with an empty configuration.

The following Makefile targets exist for managing the configuration:
- `conf_install_global`: Copy config from git to /etc
- `conf_install_local`: Copy config from git to ~/.config
- `conf_checkin_local`: Copy config from ~/.config to git

PS: agbplay no longer uses .ini. It now uses .json files instead.
