### ISSUE TITLE
Tag Inheritance

### ISSUE THREAD

**Issue by SethBarberee** [ipatix/agbplay#34]
https://github.com/ipatix/agbplay/blob/dfdce57f969151e1697e877d29cb4442e6613908/agbplay.ini#L330

So `B24P` is the Europe version of pmd-red. I've been working on the pmd-red decomp which is USA (`B24E`).

Is there any way to inherit one section to another? Currently, I just c/p the section under the header that agbplay created when I first ran it.

Not really a deal breaker. Just was curious, hah.

**Comment by ipatix** [comment]
It's on the TODO list and will probably happen if we move to a more advanced format than .ini. I can't give any esimates when I'm going to do it though.

**Comment by ipatix** [comment]
Apparently I was motivated today:
545ee68aba81b6053240c1c5cd597b7cc3e63afa
727bf61b43798b31705f43916415b711719570e0

I ported configuration to JSON and the scheme now supports a playlist with multiple games associated. Check README.md for details (`games` property).
