### ISSUE TITLE
.JSON Playlists not working?

### ISSUE THREAD

**Issue by Dippy0615** [ipatix/agbplay#35]
I compiled a newer version of agbplay because I had an older version. It's great and all, but the .JSON playlists don't seem to be working. Even when I use roms that have the same rom code as in the .JSON file it doesn't seem to work. I don't know if I did something incorrectly on my end that made it so that this feature isn't working, but I thought I'd just let you know.
Btw, I'm on Windows 10, if that helps at all.

**Comment by ipatix** [comment]
Just to sort things out: When you load any game of your choice, edit the playlist, and the close the game: Do the settings persist when you open the game one more time?

**Comment by Dippy0615** [comment]
> Just to sort things out: When you load any game of your choice, edit the playlist, and the close the game: Do the settings persist when you open the game one more time?

The settings don't seem to persist. When I change edit the playlist and change things like sample rate or rom codes and open games up, nothing seems to have changed at all.

**Comment by ipatix** [comment]
Does the file `~/.config/agbplay.json` exist?

**Comment by Dippy0615** [comment]
> Does the file `~/.config/agbplay.json` exist?

The .JSON file exists. I don't have a config folder for it, if that is what you mean.

**Comment by ipatix** [comment]
I can't follow. If the file exists the config folder HAS to exist, otherweise the file wouldn't be where it is.

One more thing though: What happens if you are in agbplay and press "f". Does it show a message about the config being saved?

**Comment by Dippy0615** [comment]
> I can't follow. If the file exists the config folder HAS to exist, otherweise the file wouldn't be where it is.
> 
> One more thing though: What happens if you are in agbplay and press "f". Does it show a message about the config being saved?

When I do that, the program closes and in the command prompt it says "Error while writing agbplay.json: No such file or directory"

**Comment by ipatix** [comment]
What does `readlink -f ~/.config/agbplay.json` show?

**Comment by Dippy0615** [comment]
Doing that doesn't show anything. I think I may have done something wrong here.

**Comment by ipatix** [comment]
Okay, are you sure that the `.config` directory exists in your home directory? Because to me it seems that it does not.

So I would suggest you do a `mkdir -p ~/.config`, start agbplay again and check if loading/saving JSON works.

**Comment by Dippy0615** [comment]
> Okay, are you sure that the `.config` directory exists in your home directory? Because to me it seems that it does not.
> 
> So I would suggest you do a `mkdir -p ~/.config`, start agbplay again and check if loading/saving JSON works.

I created the .config folder and things seem to work now! Thank you so much. I was not aware that I needed to make a .config folder.

**Comment by ipatix** [comment]
Yeah, I will leave this issue open though and put a fix in agbplay so that it creates this directory if not existant.
