### ISSUE TITLE
error wile compiling 

### ISSUE THREAD

**Issue by Littlemac123** [ipatix/agbplay#36]
![Screenshot_2020-12-13_05-58-26](https://user-images.githubusercontent.com/39867553/102009881-6b0d5280-3d08-11eb-811c-fcd10c0f5f58.png)
i get this error compiling this, i use linuxmint 20 Xfce

**Comment by ipatix** [comment]
So you have `libjsoncpp-dev` installed?

**Comment by Littlemac123** [comment]
ayy it works thanks. just a little request, can you please add all the repos you need to install to make it in your read me? it was hard for a normal user like me to find them all

**Comment by ipatix** [comment]
The libjsoncpp is already mentioned there. Was there anything else missing?

**Comment by Littlemac123** [comment]
no theres not, im just stupid and just now found it
