### ISSUE TITLE
FATAL ERROR on streaming thread: Nested track calls are not allowed

### ISSUE THREAD

**Issue by ShinkoNet** [ipatix/agbplay#37]
When playing songs found in romhacks such as Touhou Puppet Play Enhanced Reloaded (which has a lot of custom music I'd like to record), some tracks skip mid-way through with the error:
`FATAL ERROR on streaming thread: Nested track calls are not allowed:  0x C0A02A`
You can replicate this by loading this romhack (version 6.8A is fine) and then playing the Ending Credits track loaded in the playlist.

**Comment by ipatix** [comment]
I probably just have to get around to implement that particular feature. I hope I'll get time to do that some time soon.

**Comment by ipatix** [comment]
Fix coming soon since I'm rewriting the track data parser.

**Comment by ShinkoNet** [comment]
Great to hear!

**Comment by ipatix** [comment]
Oh, I actually forgot this issue and I already fixed this a while ago.

**Comment by ipatix** [comment]
I think I fixed this a month ago in here: 16861dccd590c915a3c722af125172cbb14fff7e

Please test on the current master and see if it works as expected.

**Comment by ipatix** [comment]
Due to no reply and my belief that this is fixed I'm going to close this.

**Comment by ShinkoNet** [comment]
Ah yeah, sorry for no reply. I've been trying to test but the program freezes upon playback (works as root but no sound there via pulseaudio so I can't check easily) so I can't confirm if it was fixed.
