### ISSUE TITLE
Per-track mute in the player

### ISSUE THREAD

**Issue by Sanqui** [ipatix/agbplay#4]
It would be neat if you could press "m" when over a track and have it muted.  Would help with transcribing songs and figuring out the meanings of individual voices.

**Comment by ipatix** [comment]
I already planned that feature (hence why there is an 'x' per track) when I initially wrote the first pieces of the program but for some reason lost track of it. I'll hopefully implement that as soon as possible but I'll be very busy the next week. After that I'll hopefullt get some time to work on that.

**Comment by Sanqui** [comment]
Sounds good.  No worries, take your time :)

**Comment by ipatix** [comment]
Now implemented in 2de90ab
See the readme for the control keys. To jump into/out of the track list, use arrow right/left.
