### ISSUE TITLE
Having trouble compiling

### ISSUE THREAD

**Issue by Napoleon678** [ipatix/agbplay#40]
I'm trying to compile, but I get the following message:
[Compiling] obj/CGBChannel.o
make: g++: No such file or directory
make: *** [Makefile:48: obj/CGBChannel.o] Error 127

**Comment by ipatix** [comment]
Do you happen to have spaces somewhere in the repository path?

**Comment by Napoleon678** [comment]
The path I'm using is /cygdrive/c/cygwin64/agb-master. When I type in make, I get the error I mentioned in the original post. As far as I can tell, the path does not have any spaces.

**Comment by ipatix** [comment]
Can you try to edit the Makefile, remove the `@` in the line that contains `$(CXX)`, run make again, and show what the actual command line is that fails?

**Comment by Napoleon678** [comment]
I did that, and here's the error I got:
[Compiling] obj/CGBChannel.o
g++ -c -o obj/CGBChannel.o src/CGBChannel.cpp -Wall -Wextra -Wconversion -Wunreachable-code -std=c++17 -O3 -g
make: g++: No such file or directory
make: *** [Makefile:48: obj/CGBChannel.o] Error 127

**Comment by ipatix** [comment]
Is there a directory called "obj" in your agbplay folder?

**Comment by Napoleon678** [comment]
Yes. It was included in the zip file, and I didn't delete it.

**Comment by ipatix** [comment]
Oh, do you have `gcc-g++` installed and selected in the Cygwin Updater/Installer?

**Comment by Napoleon678** [comment]
I don't. I'll install it and see if anything changes.

**Comment by Napoleon678** [comment]
I was able to create the .exe, but when I try to open it, it says the code execution cannot proceed because cygportaudio-2.dll and cygjsoncpp-24.dll were not found. I made sure I have both of them installed, and I tried reinstalling the versions I have, but it keeps giving me the same error messages.

**Comment by ipatix** [comment]
How do you launch the program?

**Comment by Napoleon678** [comment]
I tried opening the .exe by double-clicking on it, and I get the error messages, but now it just says "The application was unable to start correctly (0xc000007b)."

**Comment by ipatix** [comment]
Since agbplay is compiled under the Cygwin environment, you also have to run it from the Cygwin environment. You need the command line anyway to specify the file to load.

**Comment by Napoleon678** [comment]
I see. What do I need to type in to open it?

**Comment by ipatix** [comment]
Run the program by typing `./agbplay` inthe corresponding directory.

**Comment by Napoleon678** [comment]
Okay, but now when I try to load a ROM in, it says "Terminal does not support 256 colors."

**Comment by ipatix** [comment]
- Right click on the titlebar of the Cygwin Terminal
- Click Options
- Select "Terminal" in the tree view
- Change Type to "xterm-256color"

**Comment by Napoleon678** [comment]
That fixed it. I tested it out with a few ROMs, and it doesn't look like I have any further issues. If there are, I'll open a new issue. Thanks for everything!
