### ISSUE TITLE
Label Game Boy channels

### ISSUE THREAD

**Issue by Sanqui** [ipatix/agbplay#5]
If a track is using the native Game Boy channel for its instrument, it would be neat if the tracker could show e.g. "Ch1", "Ch2" etc. somewhere.  Would make it easier to identify them and also color them accordingly when making visualization videos.

**Comment by Sanqui** [comment]
Ah, I didn't realize tracks were dynamic to that extent.  From my experience, composers seem to keep a convention of giving Game Boy channels dedicated tracks.  The situation where more than one is used is rare enough that, to conserve space, writing something like "Ch1+" would probably suffice.

**Comment by ipatix** [comment]
I'm going to close this as I don't have plans on doing this any time soon and I don't see so much of a benefit personally. If someone else is willing to implement this, I'm open for PRs but I won't do it myself.
