### ISSUE TITLE
Some sound loops seem to confuse agbplay and emit huge lengthly files

### ISSUE THREAD

**Issue by tilkinsc** [ipatix/agbplay#51]
Pokemon mystery dungeon red rescue team dumping full files (not single ones) seems to emit some very long lengthy files. 

Affected files:
```
026
027
028
029
030
031
034
035
037
117
118
119
122
127
```

They are ambient
 and 214mb - 248mb

**Comment by ipatix** [comment]
This is not a bug. The songs actually are that long.

**Comment by tilkinsc** [comment]
Thanks for confirming

**Comment by AntyMew** [comment]
Related to this, these songs are problematic because their tracks loop at different points, correct? Would it be possible to export these tracks individually with their own loop points?

**Comment by ipatix** [comment]
Even with individual loop points the export function for individual tracks should work fine. They only issue may be that the track lengths won't be correct since this is determined by the length of the first track afaik.
