### ISSUE TITLE
DKC3 Unable to find songtable

### ISSUE THREAD

**Issue by scr-trees** [ipatix/agbplay#56]
It seems agbplay is unable to automatically detect the songtable for Donkey Kong Country 3. Is there a way to manually specify an offset?

**Comment by ipatix** [comment]
There is not at the moment, but it'd probably be a good idea to add an override.

**Comment by scr-trees** [comment]
Okay. Also is it possible to pass, say, hundreds of minigsf to the playlist script at once? If so, how? And then how do you get the script to export a json file?

**Comment by scr-trees** [comment]
Just discovered that DKC3A doesn't use mp2k, but Rare's own sound engine so this issue is moot.
