### ISSUE TITLE
Option to loop song forever (without fade-out)

### ISSUE THREAD

**Issue by nicholatian** [ipatix/agbplay#6]
I would very much appreciate seamless infinite looping of a given track, given that the default (and only) behaviour is to play the looped part twice and fade out on the start of the third go-around…

On a related note, a button to loop a single track like what VLC has would be useful as well. Currently the only way to do that is to put it on its own playlist alone.

**Comment by ipatix** [comment]
Seems like a neat feature. I hope I get some free time after christmas to work on that. I'm sadly a bit busy right now but I'll get back to you ;)

**Comment by ipatix** [comment]
Well, it's long ago I know, but since then agbplay changed quite a bit. From what I recall @Kurausukun actually implemented this some time ago in #38 . I'm going to close this, but if you feel like this doesn't solve your situation, feel free to reopen.
