### ISSUE TITLE
Windows 11 issues

### ISSUE THREAD

**Issue by ilikesonicx** [ipatix/agbplay#66]
I can't play an audio from any rom because if I press O or spacebar it freezes the terminal. I also am unable to scroll and loop songs, change the sample rate or any settings. Me and a friend both tried this and we both have Windows 11 but nothing works. The only things we can do are Press A to add the song to the playlist and press E to export individual wavs to go into our files to listen to each wav to piece together the song. Is there something wrong with agbplay?

**Comment by ipatix** [comment]
Same as #63
