### ISSUE TITLE
having trouble installing

### ISSUE THREAD

**Issue by HUNTINGTHIEVES** [ipatix/agbplay#71]
I'm a bit confused and new to this when I install the zip master file I don't see the program for agb play in there could someone help me out or make a install tutorial setting this up.

**Comment by ipatix** [comment]
I currently do not provide binary releases. The download is just the source code. You have to build it yourself until agbplay 2.0 is released.

**Comment by HUNTINGTHIEVES** [comment]
Oh gottcha. Do you have a release date for when the 2.0 version will be out?

**Comment by ipatix** [comment]
I won't be starting to work on it before beginning of May, so it'll still have to wait a bit.
