### ISSUE TITLE
Soundtable for "Tetris Worlds" not detected.

### ISSUE THREAD

**Issue by kittertron** [ipatix/agbplay#73]
Tetris Worlds has an MP2K soundtable located at 0x340e5c, agbplay fails to detect it. It's stock MP2K, works with other MP2K tools, and even agbplay if modded to load a specified table. Should note, the table I specified is just BGM. Sound effects and jingles are absent from this table, suggesting there are either multiple MP2K tables, or another engine is used for SFX.

**Comment by ipatix** [comment]
agbplay didn't detect this because it would require the songtable to contain at least 20 valid songs, but Tetris only has 7. Fixed in the latest version.

**Comment by Kermalis** [comment]
Perhaps you can add a comment next to the `#define` to mention that the lowest known count is 7 in Tetris Worlds

**Comment by ipatix** [comment]
done
