### ISSUE TITLE
Implement command 0xb6 for metroid fusion and zero mission

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [ipatix/agbplay#77]
this is a custom command in fusion/zm
you can reverse-engineer what the opcode does by looking at this decomp https://github.com/YohannDR/mzm/blob/master/src/audio.c#L1373

**Comment by H-A-M-G-E-R** [comment]
it's only for fanfares to play the song after the fanfare i think, so i'll close it

**Comment by ipatix** [comment]
Any particular reason why you have closed the issue? Although I can't particulary guarantee fixing is quickly, I do think this should be fixed.

**Comment by H-A-M-G-E-R** [comment]
it's almost the exact same command as 0xb1, but plays the room music after.
